# analytics/dbt_project.yml
name: bluesky_lakehouse
version: '1.0.0'
config-version: 2

profile: bluesky_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bluesky_lakehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
